- name: Install containerd
  apt:
    name: containerd
    state: present
    update_cache: yes

- name: Criar config padrão
  shell: |
    mkdir -p /etc/containerd
    containerd config default > /etc/containerd/config.toml

- name: Ajustar SystemdCgroup (CRÍTICO)
  replace:
    path: /etc/containerd/config.toml
    regexp: 'SystemdCgroup = false'
    replace: 'SystemdCgroup = true'

- name: Restart containerd
  systemd:
    name: containerd
    state: restarted
    enabled: yes