# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket       = "k8sadmin-aws-tfstate"
    encrypt      = true
    key          = "environments/dev/iam/terraform.tfstate"
    region       = "us-east-1"
    use_lockfile = true
  }
}
