- name: Download Kiro Agent
  shell: curl -L "{{ kiro_install_url }}" | bash
  when: kiro_install_url is defined and kiro_install_url | length > 0

- name: Enable Kiro service
  systemd:
    name: kiro
    enabled: yes
    state: started
  when: kiro_install_url is defined and kiro_install_url | length > 0
